services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: quel-io:latest
    container_name: quel-io-prod
    ports:
      - "9876:80"
    volumes:
      - kelio_data:/tmp
    restart: unless-stopped

volumes:
  kelio_data:
    driver: local
